"""Services for Calendar Club backend."""

from .background_tasks import BackgroundTaskManager, get_background_task_manager
from .base import (
    EventSource,
    EventSourceRegistry,
    get_event_source_registry,
    register_event_source,
)
from .calendar import CalendarEvent, create_ics_event, create_ics_multiple
from .event_cache import (
    CachedEvent,
    EventCache,
    EventCacheService,
    get_event_cache,
    init_event_cache,
)
from .eventbrite import (
    EventbriteClient,
    EventbriteEvent,
    get_eventbrite_client,
    register_eventbrite_source,
)
from .exa_client import (
    ExaClient,
    ExaSearchResult,
    ExaWebset,
    get_exa_client,
    register_exa_source,
)
from .exa_research import (
    ExaResearchClient,
    ExaResearchResult,
    get_exa_research_client,
    register_exa_research_source,
)
from .firecrawl_agent import (
    FirecrawlAgentClient,
    get_firecrawl_agent_client,
    register_firecrawl_agent_source,
)
from .firecrawl import (
    BaseExtractor,
    FacebookExtractor,
    FirecrawlClient,
    LumaEvent,
    LumaExtractor,
    MeetupExtractor,
    PartifulExtractor,
    PoshExtractor,
    RiverExtractor,
    ScrapedEvent,
    get_facebook_extractor,
    get_firecrawl_client,
    get_luma_extractor,
    get_meetup_extractor,
    get_partiful_extractor,
    get_posh_extractor,
    get_river_extractor,
    register_facebook_source,
    register_luma_source,
    register_meetup_scraper_source,
    register_partiful_source,
    register_posh_source,
    register_river_source,
)
from .google_calendar import (
    GoogleCalendarEvent,
    GoogleCalendarService,
    get_google_calendar_service,
)
from .msgraph import (
    MSGraphAuth,
    OutlookCalendarClient,
    OutlookEvent,
    TokenInfo,
    get_msgraph_auth,
    get_outlook_client,
)
from .session import SessionManager, get_session_manager, init_session_manager
from .sse_connections import SSEConnection, SSEConnectionManager, get_sse_manager
from .temporal_parser import TemporalParser, TemporalResult

__all__ = [
    "BackgroundTaskManager",
    "get_background_task_manager",
    "CalendarEvent",
    "create_ics_event",
    "create_ics_multiple",
    "CachedEvent",
    "EventCache",
    "EventCacheService",
    "get_event_cache",
    "init_event_cache",
    "EventbriteClient",
    "EventbriteEvent",
    "get_eventbrite_client",
    "register_eventbrite_source",
    "EventSource",
    "EventSourceRegistry",
    "get_event_source_registry",
    "register_event_source",
    "ExaClient",
    "ExaSearchResult",
    "ExaWebset",
    "get_exa_client",
    "register_exa_source",
    "ExaResearchClient",
    "ExaResearchResult",
    "get_exa_research_client",
    "register_exa_research_source",
    "FirecrawlAgentClient",
    "get_firecrawl_agent_client",
    "register_firecrawl_agent_source",
    "BaseExtractor",
    "FirecrawlClient",
    "FacebookExtractor",
    "LumaEvent",
    "LumaExtractor",
    "MeetupExtractor",
    "PartifulExtractor",
    "PoshExtractor",
    "RiverExtractor",
    "ScrapedEvent",
    "get_facebook_extractor",
    "get_firecrawl_client",
    "get_luma_extractor",
    "get_meetup_extractor",
    "get_partiful_extractor",
    "get_posh_extractor",
    "get_river_extractor",
    "register_facebook_source",
    "register_luma_source",
    "register_meetup_scraper_source",
    "register_partiful_source",
    "register_posh_source",
    "register_river_source",
    "GoogleCalendarEvent",
    "GoogleCalendarService",
    "get_google_calendar_service",
    "MSGraphAuth",
    "OutlookCalendarClient",
    "OutlookEvent",
    "TokenInfo",
    "get_msgraph_auth",
    "get_outlook_client",
    "SessionManager",
    "get_session_manager",
    "init_session_manager",
    "SSEConnection",
    "SSEConnectionManager",
    "get_sse_manager",
    "TemporalParser",
    "TemporalResult",
]
